services:
  metadata:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5422:5432"
    command: ["postgres", "-c", "max_connections=4000"]
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

  shard_0:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5430:5432"
    command: ["postgres", "-c", "max_connections=4000"]
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

  shard_1:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    command: ["postgres", "-c", "max_connections=4000"]
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

  shard_2:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "max_connections=4000"]

  shard_3:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "max_connections=4000"]
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

  shard_4:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    command: ["postgres", "-c", "max_connections=4000"]
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

  shard_5:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    command: ["postgres", "-c", "max_connections=4000"]
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
