version: '3.7'

x-common-variables: &common-variables
  CHAIN_ID: mainnet
  DATABASE_URL: postgres:5432
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password
  DATABASE_NAME: near_data
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

  NEAR_RPC_URL: https://rpc.mainnet.near.org
  ARCHIVAL_NEAR_RPC_URL: https://archival-rpc.mainnet.near.org
  AWS_BUCKET_NAME: near-lake-data-mainnet
  RUST_LOG: info

services:
  rpc-server:
    build:
      context: ../
      dockerfile: rpc-server/Dockerfile
      args:
        features: "postgres_db"
    environment:
      <<: *common-variables
      SERVER_PORT: 8000
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: on-failure

  state-indexer:
    build:
      context: ../
      dockerfile: state-indexer/Dockerfile
      args:
        features: "postgres_db"
    environment:
      <<: *common-variables
      STATE_INDEXER_ID: state-indexer-local
    command: [ "from-interruption" ]
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: on-failure

  tx-indexer:
    build:
      context: ../
      dockerfile: tx-indexer/Dockerfile
      args:
        features: "postgres_db"
    environment:
      <<: *common-variables
      TX_INDEXER_ID: tx-indexer-local
    command: [ "from-interruption" ]
    ports:
      - 8081:8081
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
